/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/w8KpJNarOEw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Temperature() {
  return (
    (<div className="flex items-center space-x-2">
      <ThermometerIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
      <div className="text-2xl font-semibold leading-none -translate-y-px">
        4.2
        <span className="text-base font-medium translate-y-0.5">°C</span>
      </div>
    </div>)
  );
}

function ThermometerIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M14 4v10.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0Z" />
    </svg>)
  );
}
